### ISSUE TITLE
Vuetify 1.2.x?

### ISSUE THREAD

**Issue by brandondube** [ndamjan/vuetify-treeview-example#2]
It would be awesome to have this pulled into the vuetify repo with support for the current release of vuetify!

**Comment by ndamjan** [comment]
Hi, the guys from Vuetify team are already working on an official treeview implementation. You can see the sneak peek in the twitter status:

https://twitter.com/vuetifyjs/status/1040082107811409920

And here is the relevant pull request:

https://github.com/vuetifyjs/vuetify/pull/5031

**Comment by brandondube** [comment]
Thanks!
